// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSy8cFhI4UmX_5tWW8hc6_ApdQ6_su2sE',
    appId: '1:947110896002:web:8549edd6b7da6f5f986f9b',
    messagingSenderId: '947110896002',
    projectId: 'thrive-72525',
    authDomain: 'thrive-72525.firebaseapp.com',
    databaseURL: 'https://thrive-72525-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrive-72525.firebasestorage.app',
    measurementId: 'G-GRY4FG0EZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXlIZc7-SAzuh1y4_AxfeJRTEd1TedzEY',
    appId: '1:947110896002:android:8b3f1e4ce8712efb986f9b',
    messagingSenderId: '947110896002',
    projectId: 'thrive-72525',
    databaseURL: 'https://thrive-72525-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrive-72525.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdjHVHjF3dQPbIxq0d7DKQauTK8ReF8Kc',
    appId: '1:947110896002:ios:e37551783338b6fa986f9b',
    messagingSenderId: '947110896002',
    projectId: 'thrive-72525',
    databaseURL: 'https://thrive-72525-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrive-72525.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdjHVHjF3dQPbIxq0d7DKQauTK8ReF8Kc',
    appId: '1:947110896002:ios:e37551783338b6fa986f9b',
    messagingSenderId: '947110896002',
    projectId: 'thrive-72525',
    databaseURL: 'https://thrive-72525-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrive-72525.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSy8cFhI4UmX_5tWW8hc6_ApdQ6_su2sE',
    appId: '1:947110896002:web:a156cf825bfd169e986f9b',
    messagingSenderId: '947110896002',
    projectId: 'thrive-72525',
    authDomain: 'thrive-72525.firebaseapp.com',
    databaseURL: 'https://thrive-72525-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'thrive-72525.firebasestorage.app',
    measurementId: 'G-PQJHZTLVKE',
  );
}
